name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilación, Pruebas y Análisis SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para SonarQube

    - name: Configuración de Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
      
    - name: Instalar Chrome y ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb chromium-browser chromium-chromedriver
        
        # Configurar ChromeDriver
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Compilar el proyecto
      run: mvn -B compile --file pom.xml

    - name: Ejecutar pruebas y generar reporte de cobertura
      run: mvn -B test jacoco:report

    - name: Análisis con SonarQube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify sonar:sonar \
          -Dsonar.projectKey=healthtrack \
          -Dsonar.host.url=https://295e-179-60-66-122.ngrok-free.app \
          -Dsonar.token=$SONAR_TOKEN